### PR TITLE
Samuel

### PR DESCRIPTION
**Pull request by inside1D**
1. Added more styling to the page (Mostly hover effect)
2. Initialized some reducers with mock data

### CODE REVIEW

**Comment by serajsas** [comment]
Screen Shot 2023-06-09 at 6 20 53 PM
 Good job. Currently this is how it looks ^, can you please change the colors so it looks better.

**Comment by wykswr** [comment]
Deck card looks beautiful, but the tag editor's responsive design can be improved:

Screenshot 2023-06-09 at 6 17 25 PM
Screenshot 2023-06-09 at 6 14 44 PM

As you can see, when I narrow down the screen's width, the layout in the bar looks weird. And in Mobile mode, the 2 input boxes should be aligned into same width.

Overall, it looks good, you can do some change in next version if you like.

**Review by wykswr — APPROVED** [review]

**Comment by serajsas** [comment]
Also when you click add tags or remove tags, currently it does nothing, can you maybe add the functionality but without any effects?

**Comment by serajsas** [comment]
Each child in a list must have a unique key when rendered, could you also add that?

**Comment by serajsas** [comment]
For the form, you could add `e.preventDefault()` to not allow it to submit the form

**Comment by serajsas** [comment]
Overall great work 👍

**Comment by inside1D** [comment]
Thanks for the feedback folks. I think I will merge this branch for the moment just for tomorrow's demo's sake, but I will keep the things you mentioned in mind and add them.

**Pull request merged**
